md archlinux\boot
md archlinux\dev
md archlinux\etc\binfmt.d
md archlinux\etc\ca-certificates\trust-source\anchors
md archlinux\etc\ca-certificates\trust-source\blacklist
md archlinux\etc\depmod.d
md archlinux\etc\kernel\install.d
md archlinux\etc\ld.so.conf.d
md archlinux\etc\modprobe.d
md archlinux\etc\modules-load.d
md archlinux\etc\request-key.d
md archlinux\etc\ssl\private
md archlinux\etc\sysctl.d
md archlinux\etc\systemd\network
md archlinux\etc\systemd\user
md archlinux\etc\tmpfiles.d
md archlinux\etc\udev\hwdb.d
md archlinux\etc\udev\rules.d
md archlinux\home
md archlinux\mnt
md archlinux\opt
md archlinux\proc
md archlinux\root
md archlinux\run
md archlinux\srv\ftp
md archlinux\srv\http
md archlinux\sys
md archlinux\tmp
md archlinux\usr\bin\site_perl
md archlinux\usr\bin\vendor_perl
md archlinux\usr\include\uapi
md archlinux\usr\lib\binfmt.d
md archlinux\usr\lib\locale
md archlinux\usr\lib\modules-load.d
md archlinux\usr\lib\perl5\site_perl
md archlinux\usr\lib\systemd\system-shutdown
md archlinux\usr\lib\systemd\system-sleep
md archlinux\usr\local\bin
md archlinux\usr\local\etc
md archlinux\usr\local\games
md archlinux\usr\local\include
md archlinux\usr\local\lib
md archlinux\usr\local\man
md archlinux\usr\local\sbin
md archlinux\usr\local\src
md archlinux\usr\share\ca-certificates\trust-source\blacklist
md archlinux\usr\share\dbus-1\session.d
md archlinux\usr\share\dbus-1\system.d
md archlinux\usr\share\man\man2
md archlinux\usr\share\man\man4
md archlinux\usr\share\man\man6
md archlinux\usr\share\misc
md archlinux\usr\share\perl5\core_perl\CPAN\API
md archlinux\usr\share\perl5\core_perl\CPAN\Meta\History
md archlinux\usr\share\perl5\site_perl
md archlinux\usr\src
md archlinux\var\cache\pacman\pkg
md archlinux\var\empty
md archlinux\var\games
md archlinux\var\lib\dbus
md archlinux\var\lib\misc
md archlinux\var\lib\pacman\sync
md archlinux\var\local
md archlinux\var\log\journal\remote
md archlinux\var\log\old
md archlinux\var\opt
md archlinux\var\spool\mail
md archlinux\var\tmp
